/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_Akhir;
import javax.swing.*;
/**
 *
 * @author acer
 */
public class LoveTester extends javax.swing.JFrame {
    public String NamaAnda;
    public String NamaPasangan;
    public String TanggalKelahiranAnda;
    public String TanggalKelahiranPasangan;

    
    
    
    
    public void Calculate() {
        //
        
    }
    
    
    
    public LoveTester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formNama = new javax.swing.JTextField();
        formPasangan = new javax.swing.JTextField();
        tglAnda = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        blnAnda = new javax.swing.JComboBox<>();
        thnAnda = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tglPasangan = new javax.swing.JComboBox<>();
        blnPasangan = new javax.swing.JComboBox<>();
        thnPasangan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Love Tester Game");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nama Anda ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nama Pasangan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        formNama.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        formNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNamaActionPerformed(evt);
            }
        });
        getContentPane().add(formNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 510, -1));

        formPasangan.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        formPasangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPasanganActionPerformed(evt);
            }
        });
        getContentPane().add(formPasangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 500, -1));

        tglAnda.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        tglAnda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tglAnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAndaActionPerformed(evt);
            }
        });
        getContentPane().add(tglAnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Tanggal Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        blnAnda.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        blnAnda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(blnAnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 70, -1));

        thnAnda.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        thnAnda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        thnAnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thnAndaActionPerformed(evt);
            }
        });
        getContentPane().add(thnAnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Tanggal Lahir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        tglPasangan.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        tglPasangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(tglPasangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        blnPasangan.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        blnPasangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(blnPasangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, 70, -1));

        thnPasangan.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        thnPasangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        thnPasangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thnPasanganActionPerformed(evt);
            }
        });
        getContentPane().add(thnPasangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 100, -1));

        jButton1.setBackground(java.awt.Color.cyan);
        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jButton1.setText("Calculate By Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 290, 60));

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Calculate By Javanese");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 340, 60));

        jButton3.setBackground(java.awt.Color.blue);
        jButton3.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Calculate By Zodiac");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 310, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg5.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thnAndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thnAndaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thnAndaActionPerformed

    private void formNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNamaActionPerformed

    private void thnPasanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thnPasanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thnPasanganActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ByZodiac love = new ByZodiac();
        
        love.setZodiacAnda(tglAnda.getSelectedItem().toString(), blnAnda.getSelectedItem().toString());
        love.setZodiacPasangan(tglPasangan.getSelectedItem().toString(), blnPasangan.getSelectedItem().toString());
        
        love.Calculate();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ByJavanese love = new ByJavanese();
        
        love.setHariPasaranAnda(tglAnda.getSelectedItem().toString(), 
                blnAnda.getSelectedItem().toString(), thnAnda.getSelectedItem().toString());
        love.setHariPasaranPasangan(tglPasangan.getSelectedItem().toString(), 
                blnPasangan.getSelectedItem().toString(), thnPasangan.getSelectedItem().toString());
        
        love.Calculate();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formPasanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPasanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formPasanganActionPerformed

    private void tglAndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAndaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglAndaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ByName love = new ByName();
        
        love.setNamaAnda(formNama.getText());
        love.setNamaPasangan(formPasangan.getText());
        
        love.Calculate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoveTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoveTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoveTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoveTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoveTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blnAnda;
    private javax.swing.JComboBox<String> blnPasangan;
    private javax.swing.JTextField formNama;
    private javax.swing.JTextField formPasangan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> tglAnda;
    private javax.swing.JComboBox<String> tglPasangan;
    private javax.swing.JComboBox<String> thnAnda;
    private javax.swing.JComboBox<String> thnPasangan;
    // End of variables declaration//GEN-END:variables
}
